#include<stdio.h>
#include<stdlib.h>
#include <math.h>
/*
* Program that calculates random-generated number in [0..1]
* using the Linear congruence method.
* Author: Agustin Borda.
*/

/*
* Global variable that stores the last generated number
* without convert it into a number in [0..1].
*/
long long int lastGenerated;

/*
* Generates a new random number without convert it
* into a number in [0..1].
*/
long long int lcgInt(long long int a,long long int c, long long int m) {
  lastGenerated = (a*lastGenerated+c)%m;
  return lastGenerated;
}

/*
* Generates a new random number and converts it
* into a number in [0..1].
*/
double lcg(long long int a,long long int c, long long int m) {
  return lcgInt(a,c,m)/(m+0.0);
}

/*
* Sets lastGenerated with a number passed as parameter.
*/
void setSeed(long long int x) {
  lastGenerated = x;
}

/*
* Generates 10 seeds and stores into a file.
* Also, returns an array with the seeds.
* The seeds are aleatory numbers generated by the function
* lcgInt with a 1000 numbers within each seed.
*/
long long int* generateSeeds(long long int originalSeed, long long int a, long long int c, long long int m, char fileExternalName[]) {
  FILE *generatedSeeds = fopen(fileExternalName,"w");
  setSeed(originalSeed);
  static long long int result[10];
  for(int i = 0; i < 10000; i++) {
    if(i%1000 == 0) {
      long long int randNumber = lcgInt(a,c,m);
      fprintf(generatedSeeds,"%lli\n",randNumber);
      result[i/1000] = randNumber;
    }
    else {
      lcgInt(a,c,m);
    }
  }
  fclose(generatedSeeds);
  return result;
}

/**
* This function takes an array of long long ints
* (in their pointer form), prints the values in it
* and sets the seed with one of these values (choosen by the user).
*/
void selectGeneratedSeed(long long int* r) {
  for (int i = 0; i < 10; i++ ) {
    printf( "Seed %d: %lli\n", i, *(r + i));
  }
  printf("Elija la seed que desea.\n");
  int choice;
  scanf("%i", &choice);
  setSeed(*(r+choice));
}

/*
* Generates 1000 random numbers within 0 and 1 using the seed
* stored in lastGenerated.
*/
void generateNumbers(long long int a, long long int c, long long int m, char fileExternalName[]) {
  FILE *generatedNumbers = fopen(fileExternalName,"w");
  for(int i=0;i<1000;i++) {
    fprintf(generatedNumbers,"%f\n",lcg(a,c,m));
  }
  fclose(generatedNumbers);
}

/**
* Solves de Exercise 3 of the practice.
* This does the same as generateNumbers, but sets the seed
* before with a given number.
*/
void ejercicio3(long long int seed, long long int a, long long int c, long long int m, char fileExternalName[]) {
  setSeed(seed);
  generateNumbers(a,c,m,fileExternalName);
}

/**
* Executes the chi-square test for a given file.
*/
int chiSquareTest(char fileExternalName[],int numberOfEquivalenceClasses,double criticalValue) {
  int equivalenceClasses[numberOfEquivalenceClasses];
  int numberOfSamples = 0;
  double current;
  for(int i=0;i<numberOfEquivalenceClasses;i++) {
    equivalenceClasses[i] = 0;
  }
  FILE *samples = fopen(fileExternalName, "r");
  while(!feof(samples)) {
    fscanf(samples,"%lf",&current);
    numberOfSamples++;
    equivalenceClasses[(int)floor(current/(1.0/numberOfEquivalenceClasses))]++;
  }
  numberOfSamples -= 1;
  int expectedSamplesInClass = numberOfSamples / numberOfEquivalenceClasses;
  fclose(samples);
  double result = 0;
  for(int i=0;i<numberOfEquivalenceClasses;i++) {
    result += pow(equivalenceClasses[i]+0.0-expectedSamplesInClass+0.0,2)/expectedSamplesInClass;
  }
  return (result<criticalValue);
}

int main(int argc, char* argv[]) {
  long long int x0 = atoi(argv[2]);
  long long int a = atoi(argv[3]);
  long long int c = atoi(argv[4]);
  long long int m = atoi(argv[5]);

  //generates the seeds.
  long long int* seeds = generateSeeds(x0,a,c,m,"archivos_generados/generated_seeds");

  /*generates 1000 random numbers and executes chi-square test
  with 20 equivalency classes and alpha = 0.005*/
  ejercicio3(x0,a,c,m,"archivos_generados/numbers_for_chi_square_test");
  if(chiSquareTest("archivos_generados/numbers_for_chi_square_test",20,38.6)) {
    printf("Pasa el test Chi-Square con alpha = 0.005\n");
  }
  else {
    printf("No pasa el test Chi-Square con alpha = 0.005\n");
  }

  /*The user selects a seed and generates
  1000 random numbers with that seed*/
  selectGeneratedSeed(seeds);
  generateNumbers(a,c,m,"archivos_generados/generated_numbers_with_selected_seed");
  return 0;
}
